/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyRequestIdRouteImport } from './routes/verify.$requestId'
import { Route as RequestNewRouteImport } from './routes/request.new'
import { Route as RequestMechanicRouteImport } from './routes/request.mechanic'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRequestIdRoute = VerifyRequestIdRouteImport.update({
  id: '/verify/$requestId',
  path: '/verify/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestNewRoute = RequestNewRouteImport.update({
  id: '/request/new',
  path: '/request/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestMechanicRoute = RequestMechanicRouteImport.update({
  id: '/request/mechanic',
  path: '/request/mechanic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRoute
  '/requests': typeof RequestsRoute
  '/signup': typeof SignupRoute
  '/request/mechanic': typeof RequestMechanicRoute
  '/request/new': typeof RequestNewRoute
  '/verify/$requestId': typeof VerifyRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRoute
  '/requests': typeof RequestsRoute
  '/signup': typeof SignupRoute
  '/request/mechanic': typeof RequestMechanicRoute
  '/request/new': typeof RequestNewRoute
  '/verify/$requestId': typeof VerifyRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRoute
  '/requests': typeof RequestsRoute
  '/signup': typeof SignupRoute
  '/request/mechanic': typeof RequestMechanicRoute
  '/request/new': typeof RequestNewRoute
  '/verify/$requestId': typeof VerifyRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/provider'
    | '/requests'
    | '/signup'
    | '/request/mechanic'
    | '/request/new'
    | '/verify/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/provider'
    | '/requests'
    | '/signup'
    | '/request/mechanic'
    | '/request/new'
    | '/verify/$requestId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/provider'
    | '/requests'
    | '/signup'
    | '/request/mechanic'
    | '/request/new'
    | '/verify/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ProviderRoute: typeof ProviderRoute
  RequestsRoute: typeof RequestsRoute
  SignupRoute: typeof SignupRoute
  RequestMechanicRoute: typeof RequestMechanicRoute
  RequestNewRoute: typeof RequestNewRoute
  VerifyRequestIdRoute: typeof VerifyRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$requestId': {
      id: '/verify/$requestId'
      path: '/verify/$requestId'
      fullPath: '/verify/$requestId'
      preLoaderRoute: typeof VerifyRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/new': {
      id: '/request/new'
      path: '/request/new'
      fullPath: '/request/new'
      preLoaderRoute: typeof RequestNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/mechanic': {
      id: '/request/mechanic'
      path: '/request/mechanic'
      fullPath: '/request/mechanic'
      preLoaderRoute: typeof RequestMechanicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ProviderRoute: ProviderRoute,
  RequestsRoute: RequestsRoute,
  SignupRoute: SignupRoute,
  RequestMechanicRoute: RequestMechanicRoute,
  RequestNewRoute: RequestNewRoute,
  VerifyRequestIdRoute: VerifyRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
